// Respuestas crudas del Q3 2026 (congeladas del Google Form). Fuente: sheet 186o3CErXrysBMijH40Pnoq0K2C4OzxWFgA9G_WeWStE
// El dashboard recalcula sub-áreas/bloques/Basic desde estas respuestas usando q3-mapping.js.
// Regenerado 2026-08-05 con las respuestas actuales del formulario.
window.Q3_DATA = {
  quarterLabel: "Q3 2026",
  answered: {
    "01 DOCTORES": {
      city: "CDMX", tipo: "Cocina", timestamp: "24/7/2026 20:02:04",
      byQuestion: { "1": "Sí", "2": "Sí", "3": "Sí", "4": "No", "5": "Sí", "6": "Sí", "7": "Sí", "8": "Sí", "9": "Sí", "10": "Sí", "11": "Sí", "12": "Sí", "13": "Sí", "14": "Sí", "15": "Sí", "16": "Sí", "17": "No", "18": "Sí", "19": "Sí", "20": "Sí", "21": "No", "22": "Sí", "23": "Sí", "24": "Sí", "25": "Sí", "26": "Parcialmente", "27": "Sí", "28": "Sí", "29": "Sí", "30": "Sí", "31": "Sí", "32": "Sí", "33": "Sí", "34": "Sí", "35": "Sí", "36": "Sí", "37": "Sí" },
      obs: { "5": "Se realizó lavado, no se cuenta con reporte fotografico ya que es plaza comercial." }
    },
    "02 SAN ANGEL": {
      city: "CDMX", tipo: "Cocina", timestamp: "27/7/2026 18:43:47",
      byQuestion: { "1": "Sí", "2": "Sí", "3": "Sí", "4": "Sí", "5": "Sí", "6": "Parcialmente", "7": "Sí", "8": "Sí", "9": "Sí", "10": "Parcialmente", "11": "Parcialmente", "12": "Parcialmente", "13": "Parcialmente", "14": "Parcialmente", "15": "Sí", "16": "Sí", "17": "Parcialmente", "18": "Sí", "19": "Sí", "20": "Sí", "21": "No", "22": "Sí", "23": "Sí", "24": "Parcialmente", "25": "Parcialmente", "26": "Sí", "27": "Parcialmente", "28": "Sí", "29": "Sí", "30": "Sí", "31": "Sí", "32": "Parcialmente", "33": "Sí", "34": "Sí", "35": "Sí", "36": "Sí", "37": "Sí" },
      obs: { "1": "Ningún cable expuesto", "2": "Sin fugas", "3": "Cumple con todos los elementos", "4": "Abril 2026", "5": "Se cuenta con Bebbia y nos abastece de agua la plaza", "6": "Colocar malla y rejilla", "7": "Se cuenta con refuerzos cada 15 días", "8": "Se cuenta con refuerzos cada 15 días", "9": "Se cumple", "10": "Se cuentan con varios puntos de anidacion", "11": "No se cuenta con temperaturas recientes", "12": "No se cuentan en su totalidad con todas las lecturas", "13": "Tenemos varias luces fundidas en la cocina", "14": "No se cuenta con protecciones en los focos", "15": "Funcionales", "16": "Ningún equipo en desuso", "17": "No se cuenta con preventivos", "18": "Funcional", "19": "Se realiza conforme el proceso", "20": "Se cumple de forma diaria y semanal", "21": "No están rotulados", "22": "Todo en plataforma lovable", "23": "Lugar asignado y cerrado", "24": "Existen fisuras en piso", "25": "Parcialmente se deben de reparar", "26": "Sin fugas y goteras", "27": "Faltan Zoclos en paredes", "28": "Todo funcional", "30": "Si existe una separación", "31": "Ninguna", "32": "No todos cuentan con uniforme y existen entregas correctas", "33": "Todo en regla en cuanto a la entrega de uniformes", "34": "4 sillas en buen estado", "35": "Suficiente", "36": "Cambiar puerta y cerrojo", "37": "Todo cumple" }
    },
    "03 POLANCO": {
      city: "CDMX", tipo: "Cocina", timestamp: "28/7/2026 19:11:53",
      byQuestion: { "1": "Sí", "2": "Sí", "3": "Sí", "4": "Sí", "5": "Sí", "6": "Sí", "7": "No", "8": "Sí", "9": "Sí", "10": "Sí", "11": "Sí", "12": "Sí", "13": "Sí", "14": "Sí", "15": "Sí", "16": "Sí", "17": "Sí", "18": "Sí", "19": "Sí", "20": "Sí", "21": "Sí", "22": "Sí", "23": "Sí", "24": "Sí", "25": "Sí", "26": "Sí", "27": "Sí", "28": "Sí", "29": "Sí", "30": "Sí", "31": "Sí", "32": "Parcialmente", "33": "Sí", "34": "Sí", "35": "Sí", "36": "Sí", "37": "Sí" },
      obs: { "1": "Todo correcto", "2": "Sin fugas", "3": "Cumple al 100%", "4": "La cocina se abastece de tinacos de la plaza de los locales", "5": "Instalación Bebbia", "6": "Coladeras sin obstrucción", "7": "Sin plagas", "8": "Se cumple al 100%", "9": "Evaluaciones en Lovable", "10": "Puntos correstis cerrados de anidacion", "11": "Tomas de temperaturas correctas", "12": "Tomas de temperatura correctas", "13": "Toda las luminarias correctas", "14": "Los focos tienen protección", "15": "Extracción funcional", "16": "Ningún equipo dañado", "17": "Contamos con servicios correctivos", "18": "Se realiza conforme el proceso", "19": "Se realiza conforme al proceso", "20": "Se valida con libro de calidad", "21": "Identificación correcta", "22": "Todas la evaluaciones en Lovable", "23": "Identificado", "24": "Sin grietas ni fisuras", "25": "Paredes sin grietas", "26": "Techos sin goteras", "27": "Todo cuenta con zoclo", "28": "Sin óxido", "29": "Todo en orden", "30": "Ninguna", "31": "Todo correcto", "32": "No todos cuentan con el uniforme", "33": "La dotación se realiza conforme el proceso", "34": "Si cuentan con espacio para bebidas y para comer", "35": "Menaje abastecido", "36": "Todo abastecido", "37": "Abastecidos" }
    },
    "04 SANTA FE": {
      city: "CDMX", tipo: "Cocina", timestamp: "25/7/2026 21:20:58",
      byQuestion: { "1": "Sí", "2": "Sí", "3": "Sí", "4": "Sí", "5": "Parcialmente", "6": "Sí", "7": "Sí", "8": "Sí", "9": "Sí", "10": "Parcialmente", "11": "Sí", "12": "Sí", "13": "Sí", "14": "Sí", "15": "Parcialmente", "16": "Sí", "17": "No", "18": "Sí", "19": "Sí", "20": "Sí", "21": "Sí", "22": "Sí", "23": "Sí", "24": "Parcialmente", "25": "Parcialmente", "26": "Sí", "27": "Sí", "28": "Sí", "29": "Sí", "30": "Sí", "31": "Sí", "32": "Sí", "33": "Sí", "34": "Sí", "35": "Sí", "36": "Sí", "37": "Sí" },
      obs: { "5": "Cuenta con filtro de agua nuevo.", "15": "Extracción principal no funciona correctamente. Potencia muy baja" }
    },
    "05 COAPA": {
      city: "CDMX", tipo: "Cocina", timestamp: "27/7/2026 17:37:40",
      byQuestion: { "1": "Sí", "2": "Sí", "3": "Sí", "4": "Sí", "5": "Sí", "6": "Sí", "7": "No", "8": "Sí", "9": "Sí", "10": "Parcialmente", "11": "Parcialmente", "12": "Sí", "13": "Parcialmente", "14": "Parcialmente", "15": "Parcialmente", "16": "Parcialmente", "17": "No", "18": "Sí", "19": "Sí", "20": "Sí", "21": "Sí", "22": "Sí", "23": "Sí", "24": "Sí", "25": "Parcialmente", "26": "Sí", "27": "No", "28": "Sí", "29": "Sí", "30": "Parcialmente", "31": "Sí", "32": "Sí", "33": "Sí", "34": "No", "35": "Parcialmente", "36": "Sí", "37": "Sí" },
      obs: { "9": "Capacitación en plataforma digital", "10": "Se necesita reparar huevos o espacios de tornillería pasada.", "15": "Extracción no tiene la fuerza suficiente.", "20": "Se realiza envío en grupo de whats app y se realiza libro de calidad.", "34": "Por espacio de cocina equipo no cuenta con un área para comer." }
    },
    "06 SATELITE": {
      city: "CDMX", tipo: "Cocina", timestamp: "30/7/2026 10:02:23",
      byQuestion: { "1": "Sí", "2": "Sí", "3": "Parcialmente", "4": "Sí", "5": "Sí", "6": "Sí", "7": "No", "8": "Sí", "9": "Sí", "10": "Sí", "11": "Sí", "12": "Sí", "13": "Sí", "14": "Parcialmente", "15": "No", "16": "Parcialmente", "17": "No", "18": "Sí", "19": "Sí", "20": "Sí", "21": "Sí", "22": "Sí", "23": "Sí", "24": "Sí", "25": "Sí", "26": "Parcialmente", "27": "Parcialmente", "28": "Sí", "29": "Sí", "30": "Sí", "31": "Sí", "32": "Sí", "33": "Sí", "34": "Sí", "35": "Sí", "36": "Parcialmente", "37": "Sí" },
      obs: { "1": "Sin cables expuestos.", "2": "Cocina sin fugas, instalaciones en buen estado.", "3": "Dispensadores (Jabón, Gel) no funcionan", "9": "Capacitación en plataforma digital.", "15": "Extracción mayor no funciona, esto genera demasiado calor dentro de la cocina.", "16": "Baño Maria Horno bajo estufa", "18": "No se cuenta con el plan de mantenimiento pero se cuenta con comprobantes de limpieza y retiro de residuos.", "23": "Se realiza retiro de basura varias veces al día, contenedor en espacio de plaza comercial.", "36": "Falta la tapa del contenedor de agua." }
    },
    "09 CHURUBUSCO": {
      city: "CDMX", tipo: "Cocina", timestamp: "24/7/2026 15:52:15",
      byQuestion: { "1": "No", "2": "Sí", "3": "Sí", "4": "Sí", "5": "Sí", "6": "Sí", "7": "No", "8": "Sí", "9": "Sí", "10": "Parcialmente", "11": "Sí", "12": "Sí", "13": "Sí", "14": "Sí", "15": "Parcialmente", "16": "Sí", "17": "No", "18": "Sí", "19": "Sí", "20": "Sí", "21": "Sí", "22": "Sí", "23": "Sí", "24": "Parcialmente", "25": "No", "26": "Parcialmente", "27": "Sí", "28": "Sí", "29": "Sí", "30": "Sí", "31": "Sí", "32": "Sí", "33": "Parcialmente", "34": "Sí", "35": "Sí", "36": "Parcialmente", "37": "Sí" },
      obs: { "4": "Comprobante de resultados no fue enviado a cocina.", "33": "Actas de entrega las consolida RH" }
    },
    "10 SAN JERONIMO": {
      city: "CDMX", tipo: "Cocina", timestamp: "4/8/2026 16:33:56",
      byQuestion: { "1": "Parcialmente", "2": "Sí", "3": "Sí", "4": "Sí", "5": "Sí", "6": "Parcialmente", "7": "No", "8": "Sí", "9": "Sí", "10": "Sí", "11": "Sí", "12": "No", "13": "Sí", "14": "Parcialmente", "15": "Sí", "16": "Sí", "17": "No", "18": "Sí", "19": "Sí", "20": "Sí", "21": "No", "22": "Sí", "23": "Sí", "24": "Parcialmente", "25": "Sí", "26": "Parcialmente", "27": "No", "28": "Sí", "29": "Sí", "30": "Sí", "31": "Sí", "32": "Sí", "33": "Sí", "34": "Sí", "35": "Sí", "36": "Sí", "37": "Sí" },
      obs: { "6": "Tuberías viejas.. causan obstrucción seguido", "21": "Falta colocar el letrero", "23": "La basura se almacena fuera de cocina en contenedor especial para basura", "26": "Se reparo la lamina de arriba, pero siguen algunas filtraciones cerca de la Campana que generan goteras y daños en el cielo falso" }
    },
    "11 AZCAPOTZALCO": {
      city: "CDMX", tipo: "Cocina", timestamp: "24/7/2026 14:23:26",
      byQuestion: { "1": "No", "2": "Sí", "3": "Sí", "4": "Sí", "5": "Sí", "6": "Sí", "7": "No", "8": "Sí", "9": "Sí", "10": "Sí", "11": "Parcialmente", "12": "Sí", "13": "Sí", "14": "Sí", "15": "Sí", "16": "Sí", "17": "Sí", "18": "Sí", "19": "Sí", "20": "Sí", "21": "Sí", "22": "Sí", "23": "Sí", "24": "Sí", "25": "Sí", "26": "Sí", "27": "Sí", "28": "Sí", "29": "Sí", "30": "Sí", "31": "Sí", "32": "Sí", "33": "Sí", "34": "Sí", "35": "Sí", "36": "Sí", "37": "Parcialmente" },
      obs: { "1": "Todo en orden", "2": "Todo en orden", "3": "Cumple al 100%", "4": "No", "5": "La cocina se encuentra en una plaza y la administración realiza el lavado de cisterna además existe Bebbia en la cocina", "6": "Ampliar más la coladera", "7": "Sin plagas", "8": "Se cuenta con programa mensual y se cumple", "9": "Se cuenta con evaluaciones en lovable", "10": "Todo cubierto y sin plagas en cocina", "11": "Temperaturas correctas", "12": "Lectura tres veces al día", "13": "Todas las luminarias activas", "14": "Todas con protección", "15": "Funcionales", "16": "Ningún equipo dañado", "17": "Solo existen por el momento correctivos", "18": "Periódicamente se realiza este mantenimientos", "19": "Secrwsliza de forma diaria, semanal y mensual", "20": "Alineado con libro de calidad", "21": "Botes completos y rotulados", "22": "Certificación en lovable", "23": "Aislado del sanitario y líneas de producción", "24": "Todo correcto", "25": "Pintura y resane al 100%", "26": "Son filtraciones", "27": "Zoclos colocados correctamente", "28": "Algunos desgastados por el uso, pero aún funcionales", "29": "Funcionales", "30": "Separación correcta", "31": "Orden y acomodo", "32": "Uniformes entregados y completos", "33": "Ninguna las entregas son puntuales", "34": "Ninguna, existe el área acondicionada", "35": "Menaje para personal completo", "36": "Baño abastecido y limpio", "37": "Por lo regular las sanitas faltan" }
    },
    "12 DEL VALLE": {
      city: "CDMX", tipo: "Cocina", timestamp: "28/7/2026 15:55:28",
      byQuestion: { "1": "Sí", "2": "Sí", "3": "Sí", "4": "Sí", "5": "Sí", "6": "Sí", "7": "No", "8": "Sí", "9": "Sí", "10": "Sí", "11": "Sí", "12": "Parcialmente", "13": "Sí", "14": "Parcialmente", "15": "Sí", "16": "Sí", "17": "Sí", "18": "Sí", "19": "Sí", "20": "Sí", "21": "No", "22": "Sí", "23": "Sí", "24": "Sí", "25": "Sí", "26": "Sí", "27": "Sí", "28": "Sí", "29": "Sí", "30": "Sí", "31": "Sí", "32": "Parcialmente", "33": "Sí", "34": "Sí", "35": "Sí", "36": "Sí", "37": "Sí" },
      obs: { "1": "Todo correcto en cuanto a sustenta eléctrico", "2": "Todo correcto y sin fugas", "3": "Cuenta con todo", "4": "El último registro que se tiene es de 23 Junio 2026", "5": "Tienen filtros Bebbia", "6": "Falta colocar malla en coladera", "7": "No se cuenta con plaga en esta cocina", "8": "Se cumple conforme el proceso de calendario", "9": "Foodies capacitados", "10": "Se resanaron paredes", "11": "Temperaturas correctas", "12": "No están actualizados al día", "13": "Iluminación correcta en toda la cocina", "14": "No se cuenta con protección en campana", "15": "Funcionales al 100%", "16": "Ningún equipo dañado o en desuso", "17": "Solamente existen mantenimientos correctivos", "18": "Limpieza mensual", "19": "Limpieza reflejada en libro de calidad", "20": "Se refleja en formato y libro de calidad", "21": "Los botes no están rotulados", "22": "Exámenes concluidos en lovable", "23": "Basura aislada", "24": "Uso sin fisuras y grietas", "25": "Todo con resane", "26": "Sin goteras y escurrimientos", "27": "Todo con zoclo", "28": "Sin óxido", "29": "Lockers bien mantenidos", "30": "Separación correcta", "31": "Sin observación", "32": "No cuentan con mandil blanco", "33": "Se realiza conforme al proceso", "34": "Se cuenta con espacio de comedor", "35": "Menaje exclusivo para los foodies", "36": "Baño limpio y bien mantenido", "37": "Insumos correctos" }
    },
    "14 JARDINES": {
      city: "CDMX", tipo: "Cocina", timestamp: "29/7/2026 16:54:25",
      byQuestion: { "1": "Sí", "2": "Sí", "3": "Sí", "4": "No", "5": "Sí", "6": "Sí", "7": "No", "8": "Sí", "9": "Sí", "10": "Sí", "11": "Sí", "12": "Sí", "13": "Sí", "14": "No", "15": "Sí", "16": "Sí", "17": "Sí", "18": "Sí", "19": "Sí", "20": "Sí", "21": "Sí", "22": "Sí", "23": "Sí", "24": "Parcialmente", "25": "Sí", "26": "Sí", "27": "No", "28": "Sí", "29": "Sí", "30": "Parcialmente", "31": "Sí", "32": "Parcialmente", "33": "Sí", "34": "Sí", "35": "Sí", "36": "Sí", "37": "Sí" },
      obs: { "6": "Falta la tapa de una", "9": "No me dejó tomar la foto Pero se llevan a cabo en la plataforma de lovable", "16": "Se realizan los rto todos los días", "18": "Le falta la base, está sobre unos tabiques, el proveedor quedó en llevarlo", "22": "No logré subir la foto Pero las capacitaciones están al 100 en la.plataforma de lovable", "32": "Faltan tallas de uniforme más grande", "36": "Se utilizan los baños de la plaza" }
    },
    "15 LINDAVISTA": {
      city: "CDMX", tipo: "Cocina", timestamp: "24/7/2026 18:22:20",
      byQuestion: { "1": "Sí", "2": "Sí", "3": "Sí", "4": "No", "5": "No", "6": "Sí", "7": "No", "8": "Sí", "9": "Sí", "10": "Sí", "11": "Sí", "12": "Parcialmente", "13": "Sí", "14": "No", "15": "Sí", "16": "Sí", "17": "Sí", "18": "Sí", "19": "Sí", "20": "Sí", "21": "Parcialmente", "22": "Sí", "23": "No", "24": "Sí", "25": "Sí", "26": "Sí", "27": "Sí", "28": "Sí", "29": "Sí", "30": "Sí", "31": "Sí", "32": "Parcialmente", "33": "Sí", "34": "Sí", "35": "Sí", "36": "Sí", "37": "Sí" },
      obs: { "1": "Todo correcto", "2": "Todo correcto", "3": "Cuenta con dos", "4": "No existen análisis", "5": "Nunca se ha lavado la cisterna", "6": "Solo existe una coladera en el interior de la cocina", "7": "Sin plagas", "8": "La fumigación se realiza conforme el calendario", "9": "Certificaciones en Lovable", "10": "Ya están regados al 100%", "11": "Equipos al 100%", "12": "No están los registros de congelación", "13": "Parpadeando 2 luces", "14": "Faltan protecciones en campana", "15": "Funcional", "16": "Ninguno dañado", "17": "Solamente se cuenta con mantenimientos preventivos", "18": "Se cuenta con evidencia de lavado de trampa", "19": "Actualizada", "20": "Cumpliendo", "21": "Colocarlas con Mica para mayor durabilidad", "22": "Lovable", "23": "Área de basura muy sucio", "24": "Piso correcto", "25": "Todo resanado y pintado", "26": "Sin filtraciones", "27": "Zoclos colocados correctamente", "28": "Utensilios desgastados por el uso", "29": "Todo en orden", "30": "Ninguna", "31": "Acomodo correcto", "32": "Existe entrega de uniformes. Pero no usan el mandil", "33": "Entregas correctas", "34": "Faltan sillas por desgaste", "35": "Existe menaje de personal", "36": "Baños limpios", "37": "Insumos correctos" }
    },
    "16 PEDREGAL": {
      city: "CDMX", tipo: "Cocina", timestamp: "27/7/2026 16:11:59",
      byQuestion: { "1": "Sí", "2": "Sí", "3": "Sí", "4": "Sí", "5": "Sí", "6": "Sí", "7": "Sí", "8": "Sí", "9": "Sí", "10": "Sí", "11": "Parcialmente", "12": "Parcialmente", "13": "Sí", "14": "No", "15": "Sí", "16": "Sí", "17": "Sí", "18": "Sí", "19": "Sí", "20": "Parcialmente", "21": "No", "22": "Sí", "23": "Sí", "24": "Parcialmente", "25": "Sí", "26": "Sí", "27": "Sí", "28": "Sí", "29": "Sí", "30": "Sí", "31": "Sí", "32": "Parcialmente", "33": "Sí", "34": "Sí", "35": "Sí", "36": "Sí", "37": "Sí" },
      obs: { "1": "Todo colocado en orden", "2": "Todo colocado correctamente sin fugas", "3": "Cumple", "4": "No se realiza desde 20 mayo 2024 la cobija está dentro de una plaza", "5": "Se cuenta con Bebbia", "6": "Sin obstrucciones y sin malos olores", "7": "Se cuenta con cucarachas aún y se cuenta con refuerzos", "8": "Ha disminuido significativamente", "9": "En la plataforma de lovable", "10": "Mantenimiento ya realizó las tareas sobre esta situación", "11": "No tienen el del día lunes, solo tienen los anteriores días", "12": "No cuentan con los actuales", "13": "Toda la iluminación corresponde a las mejora de cocina", "14": "No cuentan con protección en la campana", "15": "Se repararon las extracciones", "16": "No existen equipos dañados ni en desuso", "17": "No existen mantenimientos preventivos", "18": "Funcional con los servicios programados", "19": "Se cumple conforme el día", "20": "Se tiene en otro formato digital y no en físico", "21": "Botes de basura sin tapa", "22": "No todo está en lovable", "23": "Se encuentra aislado", "24": "El piso está con grietas", "25": "Ninguna", "26": "Sin goteras", "27": "Todas las paredes cuentan con Zoclos", "28": "Ninguna", "29": "Lockers en buen estado", "30": "Ninguna", "31": "Un poco desgastado pero funcional", "32": "No usan el uniforme completo y ya se les entregó", "33": "Se cumple conforme el proceso", "34": "Ninguna", "35": "Ninguna", "36": "Son las sanitarios de la plaza", "37": "La plaza cuenta con dotación de los mismos" }
    },
    "19 LA CALMA": {
      city: "Guadalajara", tipo: "Cocina", timestamp: "29/7/2026 17:21:11",
      byQuestion: { "1": "Sí", "2": "Parcialmente", "3": "Sí", "4": "No", "5": "Parcialmente", "6": "Parcialmente", "7": "Sí", "8": "Sí", "9": "Sí", "10": "No", "11": "Parcialmente", "12": "Parcialmente", "13": "Parcialmente", "14": "Sí", "15": "Parcialmente", "16": "Parcialmente", "17": "Parcialmente", "18": "Sí", "19": "Sí", "20": "Parcialmente", "21": "Parcialmente", "22": "No", "23": "Sí", "24": "Parcialmente", "25": "Parcialmente", "26": "Parcialmente", "27": "Parcialmente", "28": "Parcialmente", "29": "Parcialmente", "30": "Sí", "31": "Parcialmente", "32": "Parcialmente", "33": "No", "34": "No", "35": "Parcialmente", "36": "Sí", "37": "Sí" },
      obs: { "1": "son un foco de plaga y necesitan mantenimiento urgente", "2": "la de freidora y baño maria necesitan mantenimiento ya que son las que huelen a gas", "3": "por plaga el la ayuda visual no esta puesta", "4": "cada cierto tiempo huele muy feo por las obras publicas, huele como a agua estancada.", "5": "todo en orden", "6": "la del cuarto de empaques esta tapada y necesita arreglarse de las paredes con mosaicos caidos", "7": "por los huecos que hay en las instalaciones por tabla roca y techo aun tengo plaga", "9": "aun falta mas capacitaon para estar al 100", "10": "son varios puntos que aun deben de resanar", "11": "les hace falta una revision a la tuberia de salida de agua del refrigerador", "13": "hace falta la reparacion de varias luminarias", "14": "no se han reparado y se son muy necesarios", "15": "el estractor tiene muy poca potencia", "16": "Baño Maria de 2 espacios, Horno de 2 espacios y Freidora de 40 litros", "25": "la tabla roca necesita rezanado", "27": "hacen falta terminar de poner varios en algunos lugares aun", "28": "me hacen faltra varios utencilios", "34": "no tengo area desiganada" }
    },
    "20 ESMERALDA": {
      city: "CDMX", tipo: "Cocina", timestamp: "24/7/2026 22:53:52",
      byQuestion: { "1": "Sí", "2": "Sí", "3": "Sí", "4": "Sí", "5": "Sí", "6": "Sí", "7": "No", "8": "Sí", "9": "Sí", "10": "Sí", "11": "Sí", "12": "Sí", "13": "Sí", "14": "Parcialmente", "15": "Parcialmente", "16": "Sí", "17": "No", "18": "Sí", "19": "Sí", "20": "Sí", "21": "Sí", "22": "Sí", "23": "Parcialmente", "24": "Parcialmente", "25": "Parcialmente", "26": "Parcialmente", "27": "Parcialmente", "28": "Sí", "29": "Sí", "30": "Sí", "31": "Sí", "32": "Sí", "33": "Sí", "34": "Sí", "35": "Parcialmente", "36": "Sí", "37": "Sí" },
      obs: { "15": "Extracción no funciona correctamente, no realiza función de extracción.", "23": "Área de basura no se encuentra en lugar cerrado.", "35": "Material no es suficiente para personal en cocina. Se realiza solicitud en pedido mensual de menaje" }
    },
    "21 SANTA TERESITA": {
      city: "Guadalajara", tipo: "Cocina", timestamp: "29/7/2026 0:30:09",
      byQuestion: { "1": "Parcialmente", "2": "Parcialmente", "3": "Sí", "4": "No", "5": "Sí", "6": "No", "7": "No", "8": "Sí", "9": "Sí", "10": "Sí", "11": "Sí", "12": "Sí", "13": "No", "14": "Sí", "15": "Sí", "16": "Sí", "17": "No", "18": "No", "19": "Sí", "20": "Sí", "21": "No", "22": "Sí", "23": "Sí", "24": "Sí", "25": "Sí", "26": "Sí", "27": "No", "28": "Sí", "29": "Sí", "30": "Sí", "31": "Sí", "32": "Sí", "33": "Sí", "34": "Sí", "35": "Sí", "36": "Sí", "37": "Sí" },
      obs: { "1": "hay interruptures que estan sueltos pero sin corriente, por que los apagamos", "2": "No contamos con señalamnientos", "3": "si cuento", "4": "no lo tengo", "5": "no, funcionan bien", "6": "no todas funcionan o no tienen maya de proteccion y se les va la comida", "7": "ninguno", "8": "ninguno", "9": "no estan lo cursos", "10": "no si han sido detectados", "11": "no", "12": "no", "13": "no sirve la del baño y unas de la tarja", "14": "no los tenemos todos", "15": "no tenemos ventiladores", "16": "ninguno", "17": "no", "18": "no funciona y se va toda el agua", "19": "no", "20": "no", "21": "no tenemos letreros ni señalamientos", "22": "no la tengo prar esos son lops cursos", "23": "no", "24": "no est atn mal y si esta algo parejo", "25": "ninguna", "26": "no", "27": "no", "29": "no", "30": "no", "31": "no", "32": "no ninguno", "33": "no", "36": "no", "37": "no" }
    },
    "22 SAN NICOLAS": {
      city: "Monterrey", tipo: "Cocina", timestamp: "4/8/2026 17:19:55",
      byQuestion: { "1": "Parcialmente", "2": "Sí", "3": "Sí", "4": "Sí", "5": "Sí", "6": "Parcialmente", "7": "Sí", "8": "Sí", "9": "Sí", "10": "Sí", "11": "Sí", "12": "Sí", "13": "Sí", "14": "Sí", "15": "Sí", "16": "Parcialmente", "17": "No", "18": "No", "19": "No", "20": "Sí", "21": "Parcialmente", "22": "Sí", "23": "Sí", "24": "No", "25": "Sí", "26": "Parcialmente", "27": "No", "28": "Sí", "29": "Sí", "30": "Sí", "31": "Sí", "32": "Parcialmente", "33": "Sí", "34": "Sí", "35": "Sí", "36": "Sí", "37": "Sí" },
      obs: { "1": "Hay enchufes con cables salidos con riesgo de toques", "5": "Se instalarion recientemente en todas las cocinas de la ciudad", "6": "No hay coladeras dentro o cerca de la línea de servicio para facilitar la limpieza del piso", "7": "Redujo la plaga considerablemente", "16": "Baño María eléctrico", "18": "Está fracturada de una esquina y tira mucha agua de la tarja, ya se cuenta con la misma, pero falta programar el reemplazo con el proveedor", "19": "Si se está haciendo la limpieza, falta el cronograma visible", "21": "Falta cambiar la señalización", "23": "El bote de basura se encuentra fuera de la cocina", "26": "Son de lámina y están muy altos para que se puedan limpiar por el personal", "30": "Si se encuentra la zona de lavado aparte de la línea de servicio", "34": "Se cuenta con una mesa plegable y sillas para el personal" }
    },
    "23 SANTA CATARINA": {
      city: "Monterrey", tipo: "Cocina", timestamp: "23/7/2026 15:20:46",
      byQuestion: { "1": "Sí", "2": "Sí", "3": "Parcialmente", "4": "Sí", "5": "No", "6": "No", "7": "Sí", "8": "Sí", "9": "Sí", "10": "Parcialmente", "11": "Sí", "12": "Parcialmente", "13": "Parcialmente", "14": "Sí", "15": "Sí", "16": "Sí", "17": "No", "18": "Sí", "19": "Parcialmente", "20": "Sí", "21": "No", "22": "Sí", "23": "Parcialmente", "24": "Parcialmente", "25": "Sí", "26": "Sí", "27": "Sí", "28": "Sí", "29": "Sí", "30": "Sí", "31": "Sí", "32": "Sí", "33": "Parcialmente", "34": "Sí", "35": "Sí", "36": "Parcialmente", "37": "Sí" },
      obs: { "2": "Se acaba de reparar una fuga de gas.. pero hay que reajustar la tubería de gas, porque con la eliminación de los hornos de pizza las conecciones quedaron colgando", "3": "Jaboneras", "4": "No", "6": "No hay coladeras en el piso para poder hacer limpieza profunda", "7": "Se encuentran dentro de empaques dañados de equipos de refrigeración", "13": "La iluminación es muy tenue", "14": "Tengo 6 focos fundidos", "15": "Se reparo la banda del motor recientemente, sin embargo falta la reparación del ventilador del motor de la extracción para asegurar su funcionamiento por un tiempo mas prolongado", "17": "No.. los tecnicos no dejan orden de reparación en nunguna cocina, solo se realizan mantenimientos correctivos", "23": "El area designada por la plaza es fuera de la cocina.. es un area abierta y por lo general la basura de cocina se mantiene dentro del bote, sin embargo, estamos a expensas de vandalismo o que personas ajenas a la cocina tiren o dejen basura", "25": "No.. estan en buenas condiciones", "26": "El techo de la cocina solo esta cubierto con yeso", "27": "Hay soclos quebrados" }
    },
    "24 METEPEC": {
      city: "CDMX", tipo: "Cocina", timestamp: "29/7/2026 15:05:00",
      byQuestion: { "1": "Sí", "2": "Sí", "3": "Sí", "4": "Sí", "5": "Sí", "6": "Sí", "7": "No", "8": "Sí", "9": "Sí", "10": "Sí", "11": "Sí", "12": "Parcialmente", "13": "Sí", "14": "Sí", "15": "Sí", "16": "Sí", "17": "Sí", "18": "Sí", "19": "Sí", "20": "Sí", "21": "Parcialmente", "22": "Sí", "23": "Sí", "24": "Sí", "25": "Sí", "26": "Sí", "27": "Parcialmente", "28": "Sí", "29": "Sí", "30": "Sí", "31": "Sí", "32": "Parcialmente", "33": "Sí", "34": "Sí", "35": "Sí", "36": "Sí", "37": "Sí" },
      obs: { "1": "Conexiones correctas", "2": "Tuberías sin fugas", "3": "Si cuenta con lavado de manos", "4": "Análisis del 2024", "5": "Filtros Bebbia", "6": "Solo se cuenta con coladera en tarja y carcamo", "7": "Ninguna", "8": "Se cumple conforme el calendario", "9": "Todo controlado", "10": "Se cerraron puntos de anidacion", "11": "Toma de temperatura", "12": "No están al día de hoy", "13": "Sin ninguna lámpara fundida", "14": "Todo correcto", "15": "Funcional", "16": "Horno de pizza", "17": "Solo se cuenta con mantenimiento correctivo", "18": "No se cuenta con soporte reciente", "19": "Se cumple con el proceso", "20": "Se cumple y se valida con libro de calidad", "21": "Las calcomanías que facilitaron se desprenden muy rápido", "22": "Se valida en plataforma lovable", "23": "Aislado afuera de la cocina", "24": "Sin grietas ni faltantes de losetas", "25": "Paredes con falta de mantenimiento", "26": "Sin filtraciones ni grietas", "27": "Hacen falta en algunas partes Zoclos", "28": "El colador chino con restos de óxido", "29": "Lockers correctos y en buen estado", "30": "Separado del área de comida", "31": "Menaje ordenado", "32": "No siempre traen su uniforme", "33": "La dotación de hace conforme al proceso", "34": "Si cuentan con espacio para comer", "35": "Menaje completo", "36": "Baño abastecido sin problemas", "37": "Todo completo sin faltantes" }
    },
    "25 TABACHINES": {
      city: "Guadalajara", tipo: "Cocina", timestamp: "28/7/2026 21:33:58",
      byQuestion: { "1": "No", "2": "No", "3": "Sí", "4": "No", "5": "Sí", "6": "Sí", "7": "No", "8": "Sí", "9": "Sí", "10": "Sí", "11": "Sí", "12": "Sí", "13": "Sí", "14": "Sí", "15": "Sí", "16": "Sí", "17": "Sí", "18": "Sí", "19": "Sí", "20": "Sí", "21": "Sí", "22": "Sí", "23": "Sí", "24": "Sí", "25": "Sí", "26": "Sí", "27": "Sí", "28": "Sí", "29": "Sí", "30": "Sí", "31": "Sí", "32": "Sí", "33": "Sí", "34": "Sí", "35": "Sí", "36": "Sí", "37": "Sí" },
      obs: {}
    },
    "26 CIUDAD JUDICIAL": {
      city: "Guadalajara", tipo: "Cocina", timestamp: "29/7/2026 17:47:21",
      byQuestion: { "1": "Parcialmente", "2": "Parcialmente", "3": "No", "4": "No", "5": "Sí", "6": "Parcialmente", "7": "No", "8": "Sí", "9": "Sí", "10": "No", "11": "Sí", "12": "Sí", "13": "Parcialmente", "14": "Parcialmente", "15": "Parcialmente", "16": "Parcialmente", "17": "No", "18": "Sí", "19": "Sí", "20": "Sí", "21": "No", "22": "Sí", "23": "Sí", "24": "Sí", "25": "Parcialmente", "26": "Sí", "27": "No", "28": "Sí", "29": "Sí", "30": "Sí", "31": "Sí", "32": "Sí", "33": "Sí", "34": "Sí", "35": "Sí", "36": "Sí", "37": "Sí" },
      obs: { "2": "Fuga de instalación de plancha", "9": "Equipo capacitado en plataforma digital", "15": "Extracción no funciona al 100%", "22": "Personal capacitado en plataforma digital", "23": "Área de basura fuera de cocina", "36": "Sanitarios en plaza comercial" }
    },
    "27 IZTAPALAPA": {
      city: "CDMX", tipo: "Cocina", timestamp: "27/7/2026 16:57:48",
      byQuestion: { "1": "Parcialmente", "2": "Sí", "3": "Sí", "4": "Sí", "5": "Parcialmente", "6": "Parcialmente", "7": "Sí", "8": "Sí", "9": "Sí", "10": "Parcialmente", "11": "Parcialmente", "12": "Sí", "13": "Sí", "14": "Parcialmente", "15": "Parcialmente", "16": "Parcialmente", "17": "No", "18": "Parcialmente", "19": "Sí", "20": "Sí", "21": "Sí", "22": "Sí", "23": "Parcialmente", "24": "Sí", "25": "Parcialmente", "26": "No", "27": "Sí", "28": "Sí", "29": "Sí", "30": "Sí", "31": "Sí", "32": "Sí", "33": "Sí", "34": "Sí", "35": "Sí", "36": "Sí", "37": "Sí" },
      obs: { "6": "Se realiza comentario que el wc tiene reflujo por obstrucción el tubería", "9": "Capacitación en plataforma digital.", "11": "Congelador mayor -11, congelador horizontal no garantiza temperatura.", "12": "Se realiza registro de temperatura.", "15": "Extracción se apaga unos momentos después de encender.", "16": "Freidora grande, no funciona (levanta flama)", "18": "Se regresa el agua y se sale de la tapa superior.", "26": "Techo de lamina, de tienen filtraciones", "33": "RH cuenta con las actas de entrega" }
    },
    "28 CARRETERA NACIONAL": {
      city: "Monterrey", tipo: "Cocina", timestamp: "4/8/2026 16:58:37",
      byQuestion: { "1": "Sí", "2": "Sí", "3": "Parcialmente", "4": "Sí", "5": "Sí", "6": "Parcialmente", "7": "Sí", "8": "Sí", "9": "Sí", "10": "Sí", "11": "Sí", "12": "No", "13": "Sí", "14": "Sí", "15": "Sí", "16": "Parcialmente", "17": "No", "18": "Sí", "19": "No", "20": "Sí", "21": "No", "22": "Sí", "23": "Sí", "24": "Sí", "25": "Parcialmente", "26": "Sí", "27": "No", "28": "Sí", "29": "Sí", "30": "Sí", "31": "Sí", "32": "Sí", "33": "Sí", "34": "Sí", "35": "Sí", "36": "Parcialmente", "37": "Sí" },
      obs: { "3": "Faltan dispensadores y letrero de lavado de manos", "6": "Están a desnivel y se batalla para que se vaya el agua", "14": "Faltan luces dentro de la campana de extracción", "16": "Baño maría eléctrico", "17": "No tenemos ordenes de reparación en la cocina", "19": "Si se hace la limpieza.. falta reponer el cronograma físico", "21": "Falta el letrero en los botes", "23": "El bote de basura se encuentra fuera de la cocina en un área designada por la plaza para los locatarios", "25": "Las paredes son lisas en un 80%, la parte de arriba falta alisar, son bloques", "26": "No hay filtraciones, arriba hay locales", "30": "Se encuntra separada del área de cocción", "34": "Se cuenta con una mesa plegable y sillas para el personal", "36": "No cuenta con techo el espacio del sanitario" }
    },
    "30 LINCOLN": {
      city: "Monterrey", tipo: "Cocina", timestamp: "4/8/2026 14:08:01",
      byQuestion: { "1": "Sí", "2": "Sí", "3": "Parcialmente", "4": "Sí", "5": "Sí", "6": "Parcialmente", "7": "No", "8": "Sí", "9": "Sí", "10": "Parcialmente", "11": "Sí", "12": "No", "13": "Sí", "14": "No", "15": "Parcialmente", "16": "Parcialmente", "17": "No", "18": "Sí", "19": "Sí", "20": "Sí", "21": "No", "22": "Sí", "23": "Sí", "24": "Parcialmente", "25": "Sí", "26": "No", "27": "No", "28": "Sí", "29": "Sí", "30": "Sí", "31": "Sí", "32": "Sí", "33": "Sí", "34": "Sí", "35": "Sí", "36": "Sí", "37": "Sí" },
      obs: { "6": "No hay coladeras en piso para lavar pisos a profundidad", "15": "Falta potencia en la extracción", "16": "Mesa ensaladas.. tapas dañadas", "21": "Faltan los carteles", "23": "Se encuentra aisalda por parte de la plaza", "26": "No se pueden limpiar por parte del personal por altura", "27": "No hay soclos" }
    },
    "31 MONTEJO": {
      city: "Merida", tipo: "Cocina", timestamp: "29/7/2026 19:57:28",
      byQuestion: { "1": "Parcialmente", "2": "No", "3": "Sí", "4": "Sí", "5": "Sí", "6": "Parcialmente", "7": "No", "8": "Sí", "9": "Sí", "10": "Sí", "11": "Sí", "12": "Sí", "13": "Parcialmente", "14": "No", "15": "Sí", "16": "Parcialmente", "17": "No", "18": "Sí", "19": "Sí", "20": "Sí", "21": "Parcialmente", "22": "Sí", "23": "Sí", "24": "Parcialmente", "25": "Sí", "26": "Sí", "27": "Sí", "28": "Sí", "29": "Parcialmente", "30": "No", "31": "Parcialmente", "32": "Sí", "33": "Sí", "34": "Sí", "35": "Sí", "36": "Sí", "37": "Sí" },
      obs: { "1": "Hay una extensión para poder conectar el filtro de agua", "2": "Ninguna", "3": "Ninguno", "4": "Se están haciendo las pruebas de cloro residual frecuentemente y los análisis están programados al finalizar el mes", "5": "Ninguna", "6": "Hemos tenido problemas con obstrucciones que sean resultó con desazolves y con la limpieza. Aunque no se recomendaron un cambio de las tuberías de desagüe ya que las que tenemos actualmente son muy angostas", "7": "ninguna", "9": "se han realizado todas las de lovable", "10": "no tenemos puntos detectados", "11": "Ninguna", "12": "Ninguna", "14": "Urge realizar el cambio de 22 barras que se encuentran quemadas", "15": "Al ser una cocina muy caliente have falta un ventilador industrial adicional", "16": "Un baño maría, el horno de la estufa y una mesa refrigerada", "17": "Se retoma el registro", "18": "ninguna", "20": "Ninguna", "21": "Pendiente colocar la rotulación", "22": "Todos ya tomaron los cursos de lovable", "23": "Ninguna", "25": "Ninguna", "26": "Ninguna", "28": "Ninguna", "29": "No es suficiente para la cantidad de foodies", "30": "No hay separación", "35": "ninguna", "37": "No" }
    },
    "34 TLAQUEPAQUE": {
      city: "Guadalajara", tipo: "Cocina", timestamp: "29/7/2026 15:23:21",
      byQuestion: { "1": "Sí", "2": "Sí", "3": "Sí", "4": "No", "5": "Sí", "6": "Sí", "7": "No", "8": "Sí", "9": "Sí", "10": "Sí", "11": "Sí", "12": "Sí", "13": "Sí", "14": "No", "15": "Sí", "16": "Sí", "17": "Sí", "18": "Sí", "19": "Sí", "20": "Sí", "21": "No", "22": "Sí", "23": "Sí", "24": "Sí", "25": "Parcialmente", "26": "Sí", "27": "No", "28": "Sí", "29": "Sí", "30": "Sí", "31": "Sí", "32": "Parcialmente", "33": "Sí", "34": "Parcialmente", "35": "Sí", "36": "Sí", "37": "Sí" },
      obs: { "4": "No tenemos el material para realizar las pruebas", "6": "Se tapan de alguna manera porque aunque tienen rejilla huelen muy mal", "7": "Se logró regular con mucha limpieza", "21": "Aún no llegan a la cocina", "32": "Tenemos una persona nueva a la que aún no se le entrega el uniforme", "34": "Mha nos marco que se tienen que comprar mesas aparte porque esa se utiliza en pase", "36": "Se utiliza el baño de la gasolinera" }
    },
    "37 CANEK": {
      city: "Merida", tipo: "Cocina", timestamp: "27/7/2026 20:44:02",
      byQuestion: { "1": "Parcialmente", "2": "Sí", "3": "Sí", "4": "No", "5": "Sí", "6": "Sí", "7": "Sí", "8": "Sí", "9": "Sí", "10": "Sí", "11": "Sí", "12": "Sí", "13": "Sí", "14": "No", "15": "Sí", "16": "Parcialmente", "17": "No", "18": "Sí", "19": "Parcialmente", "20": "Sí", "21": "Sí", "22": "Sí", "23": "Sí", "24": "No", "25": "Sí", "26": "Sí", "27": "No", "28": "No", "29": "Parcialmente", "30": "Sí", "31": "Sí", "32": "Sí", "33": "Sí", "34": "Sí", "35": "Parcialmente", "36": "Parcialmente", "37": "Sí" },
      obs: { "1": "Se compró una extensión de uso rudo..ya que la conexión cercana dejo de funcionar", "2": "Ninguna", "4": "Esta programado para el 31 de julio", "5": "Mantenimiento al día", "6": "No se han tenido problemas con las coladeras en bastante tiempo", "9": "ninguna", "10": "No", "11": "No", "12": "Ninguna", "13": "No", "14": "No", "15": "Funciona bien sin embargo se le sabe dar mantenimiento", "16": "Baño maría", "17": "No", "19": "Solo se lleva el registro del libro de calidad", "20": "Ninguna", "21": "No", "22": "Los cursos fueron de lovable todo el personal activo ha cumplido con sus cursos", "23": "No", "24": "Hay muchas losetas rotas y desprendidas", "25": "Le falta pintura", "29": "Empiezan a presentar óxido y daños por el.uso", "30": "No tiene demarcación en el piso pero sí se encuentran separadas", "31": "Hace falta racks para un mejor orden ya que los que habían eran de plástico y son propensos para que se anide la plaga", "32": "Ya todo el personal cuenta al menos con dos juegos", "33": "no", "35": "Ya se requiere el cambio", "36": "Hay pendiente el cambio de cerradura queda antes de finalizar el mes" }
    },
    "38 SALTILLO CENTRO": {
      city: "Monterrey", tipo: "Cocina", timestamp: "23/7/2026 18:28:59",
      byQuestion: { "1": "No", "2": "Sí", "3": "Sí", "4": "Sí", "5": "No", "6": "No", "7": "Sí", "8": "Sí", "9": "Sí", "10": "Parcialmente", "11": "Sí", "12": "No", "13": "Sí", "14": "Sí", "15": "No", "16": "Parcialmente", "17": "Sí", "18": "No", "19": "Sí", "20": "Parcialmente", "21": "No", "22": "Sí", "23": "No", "24": "Parcialmente", "25": "Sí", "26": "No", "27": "No", "28": "Sí", "29": "Sí", "30": "Sí", "31": "Sí", "32": "Sí", "33": "Sí", "34": "Sí", "35": "No", "36": "Parcialmente", "37": "Sí" },
      obs: { "1": "Enchufe con cables expuestos.. riesgo de posible corto", "6": "No hay coladeras en el piso", "16": "1", "17": "Los tecnicos no dejan orden de reparación", "18": "Tira agua por falta de mantenimiento.. no se ha limpiado la trampa en mas de 6 meses.. el proveedor de Mty ya no viene a Saltillo", "19": "Las tareas de limpieza se programan el fin de semana para la siguiente semana en cursony se van borrando conforme se avanza", "23": "El bote de basura se encuentra dentro de la cocina aislado de la zona de producción.. sin embargo.. en el local no tenemos un area para dejar el bote fuera de la cocina ya que en la banqueta nos puede multar salubridad.. sin embargo.. la basura pasa todos los días a las 6 pm.. es servicio del munici", "24": "Se encuentra raspado y con hendiduras, pero no esta fracturado.. la mayor parte del piso es hipóxico", "26": "El plafon de la cocina esta muy dañado.. hay filtraciones en la parte de arriba porque la lamina esta picada", "27": "No hay soclos en cocina", "35": "No hay platos ni cubiertos para el personal", "36": "No tiene asiento las tasas" }
    },
    "39 MONTERREY CENTRO": {
      city: "Monterrey", tipo: "Cocina", timestamp: "4/8/2026 13:11:40",
      byQuestion: { "1": "Sí", "2": "Sí", "3": "Sí", "4": "Sí", "5": "Sí", "6": "Sí", "7": "No", "8": "Sí", "9": "Sí", "10": "Sí", "11": "Sí", "12": "Parcialmente", "13": "Parcialmente", "14": "Sí", "15": "Sí", "16": "Sí", "17": "No", "18": "Sí", "19": "Parcialmente", "20": "Sí", "21": "Parcialmente", "22": "Sí", "23": "Sí", "24": "Parcialmente", "25": "Parcialmente", "26": "Parcialmente", "27": "Sí", "28": "Sí", "29": "Sí", "30": "Sí", "31": "Sí", "32": "Sí", "33": "Sí", "34": "Sí", "35": "Sí", "36": "Sí", "37": "Sí" },
      obs: { "19": "Falta reponer el plan de limpieza impreso", "23": "Se encuentra en area aparte por parte de la plaza" }
    },
    "40 JARDINES DEL VALLE": {
      city: "Monterrey", tipo: "Cocina", timestamp: "30/7/2026 15:41:02",
      byQuestion: { "1": "No", "2": "Sí", "3": "Sí", "4": "No", "5": "Sí", "6": "Sí", "7": "Sí", "8": "Sí", "9": "Sí", "10": "Parcialmente", "11": "Sí", "12": "Sí", "13": "Sí", "14": "No", "15": "Sí", "16": "Sí", "17": "Sí", "18": "Sí", "19": "Sí", "20": "Sí", "21": "Parcialmente", "22": "Sí", "23": "Sí", "24": "Parcialmente", "25": "Sí", "26": "Sí", "27": "No", "28": "Sí", "29": "Sí", "30": "Sí", "31": "Sí", "32": "Parcialmente", "33": "Sí", "34": "No", "35": "Sí", "36": "Sí", "37": "Sí" },
      obs: { "9": "La cocina tiene todo el personal con solo un mes en la cocina", "10": "Se necesitan guardapolvos", "20": "No me permite tomar la foto pero se lleva el registro en el libro de calidad", "21": "No a llegado los botes de basura", "22": "Se llevan las capacitaciones en la página de lovable", "32": "Falta la entrega al personal nuevo", "34": "No sé cuenta con mesa aparte para poder comer" }
    },
    "41 VOLCANES": {
      city: "CDMX", tipo: "Cocina", timestamp: "28/7/2026 18:13:29",
      byQuestion: { "1": "Sí", "2": "Sí", "3": "Parcialmente", "4": "No", "5": "Sí", "6": "No", "7": "Sí", "8": "Sí", "9": "Sí", "10": "Parcialmente", "11": "Sí", "12": "Sí", "13": "Parcialmente", "14": "Parcialmente", "15": "No", "16": "Parcialmente", "17": "No", "18": "Sí", "19": "Sí", "20": "Sí", "21": "Sí", "22": "Sí", "23": "Sí", "24": "Parcialmente", "25": "Parcialmente", "26": "Parcialmente", "27": "No", "28": "Sí", "29": "Sí", "30": "Sí", "31": "Parcialmente", "32": "Sí", "33": "Sí", "34": "Sí", "35": "Sí", "36": "Parcialmente", "37": "Sí" },
      obs: { "3": "No cuenta con dispensadores", "5": "No se cuenta con comprobante (plaza comercial), se realizó lavado y desinfección de cisterna.", "9": "Capacitación en plataforma digital", "16": "Refrigerador Horno estufa Freidora chica Baños maría" }
    },
    "45 ESTADIO": {
      city: "Monterrey", tipo: "Cocina", timestamp: "30/7/2026 16:17:16",
      byQuestion: { "1": "No", "2": "Parcialmente", "3": "Sí", "4": "No", "5": "Sí", "6": "Sí", "7": "No", "8": "Sí", "9": "Sí", "10": "Sí", "11": "Sí", "12": "Sí", "13": "Sí", "14": "No", "15": "Sí", "16": "Sí", "17": "Sí", "18": "Sí", "19": "Sí", "20": "Sí", "21": "Parcialmente", "22": "Sí", "23": "Parcialmente", "24": "Sí", "25": "Parcialmente", "26": "Sí", "27": "No", "28": "Sí", "29": "Sí", "30": "Sí", "31": "Sí", "32": "Sí", "33": "Sí", "34": "Parcialmente", "35": "Sí", "36": "Sí", "37": "Sí" },
      obs: { "2": "Se le a estado dando mantenimiento ya que presentaba fugas", "9": "No me deja subir la foto pero están al 100 en las capacitaciones de lovable", "21": "Acaban de llegar los bote", "22": "Están en la plataforma de lovable", "25": "Se filtra el agua de la lluvia en una de las paredes", "34": "La mesa de pase es la que utilizan para comer" }
    },
    "51 SAMARA": {
      city: "CDMX", tipo: "PF", timestamp: "27/7/2026 19:10:25",
      byQuestion: { "1": "No", "2": "Sí", "3": "Sí", "4": "Sí", "5": "Sí", "6": "Sí", "7": "No", "8": "Sí", "9": "Sí", "10": "Sí", "11": "Sí", "12": "Sí", "13": "Sí", "14": "No", "15": "Sí", "16": "Sí", "17": "No", "18": "Sí", "19": "Sí", "20": "Sí", "21": "Sí", "22": "Sí", "23": "Sí", "24": "No", "25": "Parcialmente", "26": "Sí", "27": "Parcialmente", "28": "Sí", "29": "Parcialmente", "30": "Sí", "31": "Sí", "32": "Parcialmente", "33": "Sí", "34": "No", "35": "Sí", "36": "Sí", "37": "Sí" },
      obs: { "2": "No", "3": "Todo ok", "4": "No", "5": "No", "6": "No", "7": "No tenemos ninguna en Samara", "8": "No", "9": "No ninguno", "10": "No se tiene plaga ni nunca se ha tenido", "11": "Ninguni", "12": "No. Ninguna", "13": "No ninguna", "14": "No ninguno", "15": "No ninguna", "16": "Ninguno", "17": "Que no hay calendarizados", "19": "No", "20": "No", "21": "No tenemos una tapa", "22": "No ninguno", "23": "No ninguna", "24": "No nada", "25": "En el área de lavado son de plafón y ya están humedecidas", "26": "Están limpios", "27": "No hay en la mitad de la cocina", "28": "Todo bien", "29": "No son suficientes", "30": "El área de lavado es muy pequeña", "31": "El espacio es reducido", "33": "No", "34": "No hay, comen a veces en el comedor", "35": "Tenemos suficientes", "36": "Todo bien", "37": "Ninguna" }
    },
    "52 MANACAR": {
      city: "CDMX", tipo: "PF", timestamp: "28/7/2026 19:48:18",
      byQuestion: { "1": "No", "2": "Sí", "3": "Parcialmente", "4": "Sí", "5": "Sí", "6": "Sí", "7": "No", "8": "Sí", "9": "Sí", "10": "Sí", "11": "Sí", "12": "Sí", "13": "Sí", "14": "No", "15": "Sí", "16": "Parcialmente", "17": "No", "18": "Sí", "19": "Sí", "20": "Sí", "21": "Sí", "22": "Sí", "23": "Sí", "24": "No", "25": "Sí", "26": "Sí", "27": "Sí", "28": "Sí", "29": "No", "30": "No", "31": "Sí", "32": "Parcialmente", "33": "Sí", "34": "Sí", "35": "Sí", "36": "Sí", "37": "Sí" },
      obs: { "1": "No tenemos ninguno", "2": "Ninguna ! Todo el orden", "3": "Está separada y es en la tarja de la cocina", "4": "U cuna", "5": "Ninguna", "6": "No hay", "7": "Ninguna", "8": "Ninguna", "9": "Ninguna", "10": "No tenemos puntos de acceso o anidacion", "11": "Ninguna", "12": "Todo en orden", "13": "Tenemos en orden", "14": "No", "15": "No ninguna", "16": "Baño María se descompuso ayer", "17": "No hay preventivos", "18": "Ninguna", "19": "Ninguno", "21": "Ninguno", "23": "Ninguno, se encuentra fuera de la cocina", "24": "Ninguna", "25": "Ninguna,", "26": "Ninguna", "27": "Tenemos mosaicos en todas las paredes", "29": "No hay lockers en esta cocina", "30": "La cocina es demasiado chica", "31": "Ninguna", "32": "Solo les dieron una playera y los nuevos no tienen mandil aún", "36": "Están en la plaza y si están muy limpios", "37": "Ninguna" }
    },
    "54 CENTR INTERLOMAS": {
      city: "CDMX", tipo: "PF", timestamp: "29/7/2026 14:56:10",
      byQuestion: { "1": "No", "2": "Sí", "3": "Sí", "4": "No", "5": "Sí", "6": "Sí", "7": "No", "8": "Sí", "9": "Sí", "10": "Sí", "11": "Sí", "12": "Sí", "13": "Parcialmente", "14": "Sí", "15": "Sí", "16": "Sí", "17": "Sí", "18": "Sí", "19": "Sí", "20": "Sí", "21": "Sí", "22": "Sí", "23": "Sí", "24": "Sí", "25": "Sí", "26": "Sí", "27": "Sí", "28": "Sí", "29": "Sí", "30": "Sí", "31": "Sí", "32": "Sí", "33": "Sí", "34": "Sí", "35": "Sí", "36": "Sí", "37": "Sí" },
      obs: { "1": "No", "2": "No", "5": "No", "6": "No", "7": "No", "8": "No", "9": "No", "10": "No", "11": "No", "12": "No", "13": "Focos de campana no han sido instalados", "14": "No", "15": "No", "17": "No", "19": "No", "20": "No", "21": "No", "22": "No", "23": "No" }
    }
  },
  pending: [ "13 TEC", "17 CUMBRES" ]
};
